#include <ctime>
// typedefs need to be outside the include guards to
// be visible to all files including objects.h
typedef double randomNumber_t;  // random number type

#ifndef _BRIAN_OBJECTS_H
#define _BRIAN_OBJECTS_H

#include<vector>
#include<stdint.h>
#include "synapses_classes.h"
#include "brianlib/clocks.h"
#include "network.h"
#include "rand.h"

#include <thrust/device_vector.h>
#include <curand.h>
#include <curand_kernel.h>

namespace brian {

extern size_t used_device_memory;

//////////////// clocks ///////////////////
extern Clock defaultclock;

//////////////// networks /////////////////
extern Network magicnetwork;

//////////////// dynamic arrays ///////////
extern thrust::host_vector<double> _dynamic_array_ratemonitor_1_rate;
extern thrust::device_vector<double> dev_dynamic_array_ratemonitor_1_rate;
extern thrust::host_vector<double> _dynamic_array_ratemonitor_1_t;
extern thrust::device_vector<double> dev_dynamic_array_ratemonitor_1_t;
extern thrust::host_vector<double> _dynamic_array_ratemonitor_2_rate;
extern thrust::device_vector<double> dev_dynamic_array_ratemonitor_2_rate;
extern thrust::host_vector<double> _dynamic_array_ratemonitor_2_t;
extern thrust::device_vector<double> dev_dynamic_array_ratemonitor_2_t;
extern thrust::host_vector<double> _dynamic_array_ratemonitor_3_rate;
extern thrust::device_vector<double> dev_dynamic_array_ratemonitor_3_rate;
extern thrust::host_vector<double> _dynamic_array_ratemonitor_3_t;
extern thrust::device_vector<double> dev_dynamic_array_ratemonitor_3_t;
extern thrust::host_vector<double> _dynamic_array_ratemonitor_rate;
extern thrust::device_vector<double> dev_dynamic_array_ratemonitor_rate;
extern thrust::host_vector<double> _dynamic_array_ratemonitor_t;
extern thrust::device_vector<double> dev_dynamic_array_ratemonitor_t;
extern thrust::host_vector<int32_t> _dynamic_array_spikemonitor_1_i;
extern thrust::device_vector<int32_t> dev_dynamic_array_spikemonitor_1_i;
extern thrust::host_vector<double> _dynamic_array_spikemonitor_1_t;
extern thrust::device_vector<double> dev_dynamic_array_spikemonitor_1_t;
extern thrust::host_vector<int32_t> _dynamic_array_spikemonitor_2_i;
extern thrust::device_vector<int32_t> dev_dynamic_array_spikemonitor_2_i;
extern thrust::host_vector<double> _dynamic_array_spikemonitor_2_t;
extern thrust::device_vector<double> dev_dynamic_array_spikemonitor_2_t;
extern thrust::host_vector<int32_t> _dynamic_array_spikemonitor_3_i;
extern thrust::device_vector<int32_t> dev_dynamic_array_spikemonitor_3_i;
extern thrust::host_vector<double> _dynamic_array_spikemonitor_3_t;
extern thrust::device_vector<double> dev_dynamic_array_spikemonitor_3_t;
extern thrust::host_vector<int32_t> _dynamic_array_spikemonitor_i;
extern thrust::device_vector<int32_t> dev_dynamic_array_spikemonitor_i;
extern thrust::host_vector<double> _dynamic_array_spikemonitor_t;
extern thrust::device_vector<double> dev_dynamic_array_spikemonitor_t;
extern thrust::host_vector<double> _dynamic_array_statemonitor_1_t;
extern thrust::device_vector<double> dev_dynamic_array_statemonitor_1_t;
extern thrust::host_vector<double> _dynamic_array_statemonitor_2_t;
extern thrust::device_vector<double> dev_dynamic_array_statemonitor_2_t;
extern thrust::host_vector<double> _dynamic_array_statemonitor_3_t;
extern thrust::device_vector<double> dev_dynamic_array_statemonitor_3_t;
extern thrust::host_vector<double> _dynamic_array_statemonitor_t;
extern thrust::device_vector<double> dev_dynamic_array_statemonitor_t;
extern thrust::host_vector<int32_t> _dynamic_array_synapses_1__synaptic_post;
extern thrust::device_vector<int32_t> dev_dynamic_array_synapses_1__synaptic_post;
extern thrust::host_vector<int32_t> _dynamic_array_synapses_1__synaptic_pre;
extern thrust::device_vector<int32_t> dev_dynamic_array_synapses_1__synaptic_pre;
extern thrust::host_vector<double> _dynamic_array_synapses_1_delay;
extern thrust::device_vector<double> dev_dynamic_array_synapses_1_delay;
extern thrust::host_vector<double> _dynamic_array_synapses_1_delay_1;
extern thrust::device_vector<double> dev_dynamic_array_synapses_1_delay_1;
extern thrust::host_vector<int32_t> _dynamic_array_synapses_1_N_incoming;
extern thrust::device_vector<int32_t> dev_dynamic_array_synapses_1_N_incoming;
extern thrust::host_vector<int32_t> _dynamic_array_synapses_1_N_outgoing;
extern thrust::device_vector<int32_t> dev_dynamic_array_synapses_1_N_outgoing;
extern thrust::host_vector<double> _dynamic_array_synapses_1_w_CFPKJ;
extern thrust::device_vector<double> dev_dynamic_array_synapses_1_w_CFPKJ;
extern thrust::host_vector<int32_t> _dynamic_array_synapses_2__synaptic_post;
extern thrust::device_vector<int32_t> dev_dynamic_array_synapses_2__synaptic_post;
extern thrust::host_vector<int32_t> _dynamic_array_synapses_2__synaptic_pre;
extern thrust::device_vector<int32_t> dev_dynamic_array_synapses_2__synaptic_pre;
extern thrust::host_vector<double> _dynamic_array_synapses_2_delay;
extern thrust::device_vector<double> dev_dynamic_array_synapses_2_delay;
extern thrust::host_vector<double> _dynamic_array_synapses_2_delay_1;
extern thrust::device_vector<double> dev_dynamic_array_synapses_2_delay_1;
extern thrust::host_vector<int32_t> _dynamic_array_synapses_2_N_incoming;
extern thrust::device_vector<int32_t> dev_dynamic_array_synapses_2_N_incoming;
extern thrust::host_vector<int32_t> _dynamic_array_synapses_2_N_outgoing;
extern thrust::device_vector<int32_t> dev_dynamic_array_synapses_2_N_outgoing;
extern thrust::host_vector<double> _dynamic_array_synapses_2_w_GRGO;
extern thrust::device_vector<double> dev_dynamic_array_synapses_2_w_GRGO;
extern thrust::host_vector<int32_t> _dynamic_array_synapses_3__synaptic_post;
extern thrust::device_vector<int32_t> dev_dynamic_array_synapses_3__synaptic_post;
extern thrust::host_vector<int32_t> _dynamic_array_synapses_3__synaptic_pre;
extern thrust::device_vector<int32_t> dev_dynamic_array_synapses_3__synaptic_pre;
extern thrust::host_vector<double> _dynamic_array_synapses_3_delay;
extern thrust::device_vector<double> dev_dynamic_array_synapses_3_delay;
extern thrust::host_vector<int32_t> _dynamic_array_synapses_3_N_incoming;
extern thrust::device_vector<int32_t> dev_dynamic_array_synapses_3_N_incoming;
extern thrust::host_vector<int32_t> _dynamic_array_synapses_3_N_outgoing;
extern thrust::device_vector<int32_t> dev_dynamic_array_synapses_3_N_outgoing;
extern thrust::host_vector<double> _dynamic_array_synapses_3_w_GOGR;
extern thrust::device_vector<double> dev_dynamic_array_synapses_3_w_GOGR;
extern thrust::host_vector<int32_t> _dynamic_array_synapses_4__synaptic_post;
extern thrust::device_vector<int32_t> dev_dynamic_array_synapses_4__synaptic_post;
extern thrust::host_vector<int32_t> _dynamic_array_synapses_4__synaptic_pre;
extern thrust::device_vector<int32_t> dev_dynamic_array_synapses_4__synaptic_pre;
extern thrust::host_vector<double> _dynamic_array_synapses_4_delay;
extern thrust::device_vector<double> dev_dynamic_array_synapses_4_delay;
extern thrust::host_vector<double> _dynamic_array_synapses_4_delay_1;
extern thrust::device_vector<double> dev_dynamic_array_synapses_4_delay_1;
extern thrust::host_vector<int32_t> _dynamic_array_synapses_4_N_incoming;
extern thrust::device_vector<int32_t> dev_dynamic_array_synapses_4_N_incoming;
extern thrust::host_vector<int32_t> _dynamic_array_synapses_4_N_outgoing;
extern thrust::device_vector<int32_t> dev_dynamic_array_synapses_4_N_outgoing;
extern thrust::host_vector<double> _dynamic_array_synapses_4_w_GRPKJ;
extern thrust::device_vector<double> dev_dynamic_array_synapses_4_w_GRPKJ;
extern thrust::host_vector<int32_t> _dynamic_array_synapses_5__synaptic_post;
extern thrust::device_vector<int32_t> dev_dynamic_array_synapses_5__synaptic_post;
extern thrust::host_vector<int32_t> _dynamic_array_synapses_5__synaptic_pre;
extern thrust::device_vector<int32_t> dev_dynamic_array_synapses_5__synaptic_pre;
extern thrust::host_vector<double> _dynamic_array_synapses_5_delay;
extern thrust::device_vector<double> dev_dynamic_array_synapses_5_delay;
extern thrust::host_vector<double> _dynamic_array_synapses_5_delay_1;
extern thrust::device_vector<double> dev_dynamic_array_synapses_5_delay_1;
extern thrust::host_vector<int32_t> _dynamic_array_synapses_5_N_incoming;
extern thrust::device_vector<int32_t> dev_dynamic_array_synapses_5_N_incoming;
extern thrust::host_vector<int32_t> _dynamic_array_synapses_5_N_outgoing;
extern thrust::device_vector<int32_t> dev_dynamic_array_synapses_5_N_outgoing;
extern thrust::host_vector<double> _dynamic_array_synapses_5_w_GRBS;
extern thrust::device_vector<double> dev_dynamic_array_synapses_5_w_GRBS;
extern thrust::host_vector<int32_t> _dynamic_array_synapses_6__synaptic_post;
extern thrust::device_vector<int32_t> dev_dynamic_array_synapses_6__synaptic_post;
extern thrust::host_vector<int32_t> _dynamic_array_synapses_6__synaptic_pre;
extern thrust::device_vector<int32_t> dev_dynamic_array_synapses_6__synaptic_pre;
extern thrust::host_vector<double> _dynamic_array_synapses_6_delay;
extern thrust::device_vector<double> dev_dynamic_array_synapses_6_delay;
extern thrust::host_vector<int32_t> _dynamic_array_synapses_6_N_incoming;
extern thrust::device_vector<int32_t> dev_dynamic_array_synapses_6_N_incoming;
extern thrust::host_vector<int32_t> _dynamic_array_synapses_6_N_outgoing;
extern thrust::device_vector<int32_t> dev_dynamic_array_synapses_6_N_outgoing;
extern thrust::host_vector<double> _dynamic_array_synapses_6_w_BSPKJ;
extern thrust::device_vector<double> dev_dynamic_array_synapses_6_w_BSPKJ;
extern thrust::host_vector<int32_t> _dynamic_array_synapses__synaptic_post;
extern thrust::device_vector<int32_t> dev_dynamic_array_synapses__synaptic_post;
extern thrust::host_vector<int32_t> _dynamic_array_synapses__synaptic_pre;
extern thrust::device_vector<int32_t> dev_dynamic_array_synapses__synaptic_pre;
extern thrust::host_vector<double> _dynamic_array_synapses_delay;
extern thrust::device_vector<double> dev_dynamic_array_synapses_delay;
extern thrust::host_vector<double> _dynamic_array_synapses_delay_1;
extern thrust::device_vector<double> dev_dynamic_array_synapses_delay_1;
extern thrust::host_vector<int32_t> _dynamic_array_synapses_N_incoming;
extern thrust::device_vector<int32_t> dev_dynamic_array_synapses_N_incoming;
extern thrust::host_vector<int32_t> _dynamic_array_synapses_N_outgoing;
extern thrust::device_vector<int32_t> dev_dynamic_array_synapses_N_outgoing;
extern thrust::host_vector<double> _dynamic_array_synapses_w_MFGR;
extern thrust::device_vector<double> dev_dynamic_array_synapses_w_MFGR;

//////////////// arrays ///////////////////
extern double * _array_defaultclock_dt;
extern double * dev_array_defaultclock_dt;
extern __device__ double *d_array_defaultclock_dt;
extern const int _num__array_defaultclock_dt;
extern double * _array_defaultclock_t;
extern double * dev_array_defaultclock_t;
extern __device__ double *d_array_defaultclock_t;
extern const int _num__array_defaultclock_t;
extern int64_t * _array_defaultclock_timestep;
extern int64_t * dev_array_defaultclock_timestep;
extern __device__ int64_t *d_array_defaultclock_timestep;
extern const int _num__array_defaultclock_timestep;
extern int32_t * _array_neurongroup_1_i;
extern int32_t * dev_array_neurongroup_1_i;
extern __device__ int32_t *d_array_neurongroup_1_i;
extern const int _num__array_neurongroup_1_i;
extern double * _array_neurongroup_1_s_ahp_GO;
extern double * dev_array_neurongroup_1_s_ahp_GO;
extern __device__ double *d_array_neurongroup_1_s_ahp_GO;
extern const int _num__array_neurongroup_1_s_ahp_GO;
extern double * _array_neurongroup_1_s_AMPA;
extern double * dev_array_neurongroup_1_s_AMPA;
extern __device__ double *d_array_neurongroup_1_s_AMPA;
extern const int _num__array_neurongroup_1_s_AMPA;
extern double * _array_neurongroup_1_s_NMDA_1;
extern double * dev_array_neurongroup_1_s_NMDA_1;
extern __device__ double *d_array_neurongroup_1_s_NMDA_1;
extern const int _num__array_neurongroup_1_s_NMDA_1;
extern double * _array_neurongroup_1_s_NMDA_2;
extern double * dev_array_neurongroup_1_s_NMDA_2;
extern __device__ double *d_array_neurongroup_1_s_NMDA_2;
extern const int _num__array_neurongroup_1_s_NMDA_2;
extern double * _array_neurongroup_1_V;
extern double * dev_array_neurongroup_1_V;
extern __device__ double *d_array_neurongroup_1_V;
extern const int _num__array_neurongroup_1_V;
extern double * _array_neurongroup_1_x;
extern double * dev_array_neurongroup_1_x;
extern __device__ double *d_array_neurongroup_1_x;
extern const int _num__array_neurongroup_1_x;
extern double * _array_neurongroup_1_y;
extern double * dev_array_neurongroup_1_y;
extern __device__ double *d_array_neurongroup_1_y;
extern const int _num__array_neurongroup_1_y;
extern int32_t * _array_neurongroup_2_i;
extern int32_t * dev_array_neurongroup_2_i;
extern __device__ int32_t *d_array_neurongroup_2_i;
extern const int _num__array_neurongroup_2_i;
extern double * _array_neurongroup_2_s_AHP_PKJ;
extern double * dev_array_neurongroup_2_s_AHP_PKJ;
extern __device__ double *d_array_neurongroup_2_s_AHP_PKJ;
extern const int _num__array_neurongroup_2_s_AHP_PKJ;
extern double * _array_neurongroup_2_s_AMPA;
extern double * dev_array_neurongroup_2_s_AMPA;
extern __device__ double *d_array_neurongroup_2_s_AMPA;
extern const int _num__array_neurongroup_2_s_AMPA;
extern double * _array_neurongroup_2_s_GABA;
extern double * dev_array_neurongroup_2_s_GABA;
extern __device__ double *d_array_neurongroup_2_s_GABA;
extern const int _num__array_neurongroup_2_s_GABA;
extern double * _array_neurongroup_2_V;
extern double * dev_array_neurongroup_2_V;
extern __device__ double *d_array_neurongroup_2_V;
extern const int _num__array_neurongroup_2_V;
extern int32_t * _array_neurongroup_3_i;
extern int32_t * dev_array_neurongroup_3_i;
extern __device__ int32_t *d_array_neurongroup_3_i;
extern const int _num__array_neurongroup_3_i;
extern double * _array_neurongroup_3_s_AHP_BS;
extern double * dev_array_neurongroup_3_s_AHP_BS;
extern __device__ double *d_array_neurongroup_3_s_AHP_BS;
extern const int _num__array_neurongroup_3_s_AHP_BS;
extern double * _array_neurongroup_3_s_AMPA;
extern double * dev_array_neurongroup_3_s_AMPA;
extern __device__ double *d_array_neurongroup_3_s_AMPA;
extern const int _num__array_neurongroup_3_s_AMPA;
extern double * _array_neurongroup_3_V;
extern double * dev_array_neurongroup_3_V;
extern __device__ double *d_array_neurongroup_3_V;
extern const int _num__array_neurongroup_3_V;
extern int32_t * _array_neurongroup_i;
extern int32_t * dev_array_neurongroup_i;
extern __device__ int32_t *d_array_neurongroup_i;
extern const int _num__array_neurongroup_i;
extern double * _array_neurongroup_s_ahp_GR;
extern double * dev_array_neurongroup_s_ahp_GR;
extern __device__ double *d_array_neurongroup_s_ahp_GR;
extern const int _num__array_neurongroup_s_ahp_GR;
extern double * _array_neurongroup_s_AMPA;
extern double * dev_array_neurongroup_s_AMPA;
extern __device__ double *d_array_neurongroup_s_AMPA;
extern const int _num__array_neurongroup_s_AMPA;
extern double * _array_neurongroup_s_GABA_1;
extern double * dev_array_neurongroup_s_GABA_1;
extern __device__ double *d_array_neurongroup_s_GABA_1;
extern const int _num__array_neurongroup_s_GABA_1;
extern double * _array_neurongroup_s_GABA_2;
extern double * dev_array_neurongroup_s_GABA_2;
extern __device__ double *d_array_neurongroup_s_GABA_2;
extern const int _num__array_neurongroup_s_GABA_2;
extern double * _array_neurongroup_s_NMDA;
extern double * dev_array_neurongroup_s_NMDA;
extern __device__ double *d_array_neurongroup_s_NMDA;
extern const int _num__array_neurongroup_s_NMDA;
extern double * _array_neurongroup_V;
extern double * dev_array_neurongroup_V;
extern __device__ double *d_array_neurongroup_V;
extern const int _num__array_neurongroup_V;
extern double * _array_neurongroup_x;
extern double * dev_array_neurongroup_x;
extern __device__ double *d_array_neurongroup_x;
extern const int _num__array_neurongroup_x;
extern double * _array_neurongroup_y;
extern double * dev_array_neurongroup_y;
extern __device__ double *d_array_neurongroup_y;
extern const int _num__array_neurongroup_y;
extern int32_t * _array_poissongroup_1_i;
extern int32_t * dev_array_poissongroup_1_i;
extern __device__ int32_t *d_array_poissongroup_1_i;
extern const int _num__array_poissongroup_1_i;
extern int32_t * _array_poissongroup_i;
extern int32_t * dev_array_poissongroup_i;
extern __device__ int32_t *d_array_poissongroup_i;
extern const int _num__array_poissongroup_i;
extern int32_t * _array_ratemonitor_1_N;
extern int32_t * dev_array_ratemonitor_1_N;
extern __device__ int32_t *d_array_ratemonitor_1_N;
extern const int _num__array_ratemonitor_1_N;
extern int32_t * _array_ratemonitor_2_N;
extern int32_t * dev_array_ratemonitor_2_N;
extern __device__ int32_t *d_array_ratemonitor_2_N;
extern const int _num__array_ratemonitor_2_N;
extern int32_t * _array_ratemonitor_3_N;
extern int32_t * dev_array_ratemonitor_3_N;
extern __device__ int32_t *d_array_ratemonitor_3_N;
extern const int _num__array_ratemonitor_3_N;
extern int32_t * _array_ratemonitor_N;
extern int32_t * dev_array_ratemonitor_N;
extern __device__ int32_t *d_array_ratemonitor_N;
extern const int _num__array_ratemonitor_N;
extern int32_t * _array_spikemonitor_1__source_idx;
extern int32_t * dev_array_spikemonitor_1__source_idx;
extern __device__ int32_t *d_array_spikemonitor_1__source_idx;
extern const int _num__array_spikemonitor_1__source_idx;
extern int32_t * _array_spikemonitor_1_count;
extern int32_t * dev_array_spikemonitor_1_count;
extern __device__ int32_t *d_array_spikemonitor_1_count;
extern const int _num__array_spikemonitor_1_count;
extern int32_t * _array_spikemonitor_1_N;
extern int32_t * dev_array_spikemonitor_1_N;
extern __device__ int32_t *d_array_spikemonitor_1_N;
extern const int _num__array_spikemonitor_1_N;
extern int32_t * _array_spikemonitor_2__source_idx;
extern int32_t * dev_array_spikemonitor_2__source_idx;
extern __device__ int32_t *d_array_spikemonitor_2__source_idx;
extern const int _num__array_spikemonitor_2__source_idx;
extern int32_t * _array_spikemonitor_2_count;
extern int32_t * dev_array_spikemonitor_2_count;
extern __device__ int32_t *d_array_spikemonitor_2_count;
extern const int _num__array_spikemonitor_2_count;
extern int32_t * _array_spikemonitor_2_N;
extern int32_t * dev_array_spikemonitor_2_N;
extern __device__ int32_t *d_array_spikemonitor_2_N;
extern const int _num__array_spikemonitor_2_N;
extern int32_t * _array_spikemonitor_3__source_idx;
extern int32_t * dev_array_spikemonitor_3__source_idx;
extern __device__ int32_t *d_array_spikemonitor_3__source_idx;
extern const int _num__array_spikemonitor_3__source_idx;
extern int32_t * _array_spikemonitor_3_count;
extern int32_t * dev_array_spikemonitor_3_count;
extern __device__ int32_t *d_array_spikemonitor_3_count;
extern const int _num__array_spikemonitor_3_count;
extern int32_t * _array_spikemonitor_3_N;
extern int32_t * dev_array_spikemonitor_3_N;
extern __device__ int32_t *d_array_spikemonitor_3_N;
extern const int _num__array_spikemonitor_3_N;
extern int32_t * _array_spikemonitor__source_idx;
extern int32_t * dev_array_spikemonitor__source_idx;
extern __device__ int32_t *d_array_spikemonitor__source_idx;
extern const int _num__array_spikemonitor__source_idx;
extern int32_t * _array_spikemonitor_count;
extern int32_t * dev_array_spikemonitor_count;
extern __device__ int32_t *d_array_spikemonitor_count;
extern const int _num__array_spikemonitor_count;
extern int32_t * _array_spikemonitor_N;
extern int32_t * dev_array_spikemonitor_N;
extern __device__ int32_t *d_array_spikemonitor_N;
extern const int _num__array_spikemonitor_N;
extern int32_t * _array_statemonitor_1__indices;
extern int32_t * dev_array_statemonitor_1__indices;
extern __device__ int32_t *d_array_statemonitor_1__indices;
extern const int _num__array_statemonitor_1__indices;
extern int32_t * _array_statemonitor_1_N;
extern int32_t * dev_array_statemonitor_1_N;
extern __device__ int32_t *d_array_statemonitor_1_N;
extern const int _num__array_statemonitor_1_N;
extern double * _array_statemonitor_1_V;
extern double * dev_array_statemonitor_1_V;
extern __device__ double *d_array_statemonitor_1_V;
extern const int _num__array_statemonitor_1_V;
extern int32_t * _array_statemonitor_2__indices;
extern int32_t * dev_array_statemonitor_2__indices;
extern __device__ int32_t *d_array_statemonitor_2__indices;
extern const int _num__array_statemonitor_2__indices;
extern int32_t * _array_statemonitor_2_N;
extern int32_t * dev_array_statemonitor_2_N;
extern __device__ int32_t *d_array_statemonitor_2_N;
extern const int _num__array_statemonitor_2_N;
extern double * _array_statemonitor_2_V;
extern double * dev_array_statemonitor_2_V;
extern __device__ double *d_array_statemonitor_2_V;
extern const int _num__array_statemonitor_2_V;
extern int32_t * _array_statemonitor_3__indices;
extern int32_t * dev_array_statemonitor_3__indices;
extern __device__ int32_t *d_array_statemonitor_3__indices;
extern const int _num__array_statemonitor_3__indices;
extern int32_t * _array_statemonitor_3_N;
extern int32_t * dev_array_statemonitor_3_N;
extern __device__ int32_t *d_array_statemonitor_3_N;
extern const int _num__array_statemonitor_3_N;
extern double * _array_statemonitor_3_V;
extern double * dev_array_statemonitor_3_V;
extern __device__ double *d_array_statemonitor_3_V;
extern const int _num__array_statemonitor_3_V;
extern int32_t * _array_statemonitor__indices;
extern int32_t * dev_array_statemonitor__indices;
extern __device__ int32_t *d_array_statemonitor__indices;
extern const int _num__array_statemonitor__indices;
extern int32_t * _array_statemonitor_N;
extern int32_t * dev_array_statemonitor_N;
extern __device__ int32_t *d_array_statemonitor_N;
extern const int _num__array_statemonitor_N;
extern double * _array_statemonitor_V;
extern double * dev_array_statemonitor_V;
extern __device__ double *d_array_statemonitor_V;
extern const int _num__array_statemonitor_V;
extern int32_t * _array_synapses_1_N;
extern int32_t * dev_array_synapses_1_N;
extern __device__ int32_t *d_array_synapses_1_N;
extern const int _num__array_synapses_1_N;
extern int32_t * _array_synapses_2_N;
extern int32_t * dev_array_synapses_2_N;
extern __device__ int32_t *d_array_synapses_2_N;
extern const int _num__array_synapses_2_N;
extern int32_t * _array_synapses_3_N;
extern int32_t * dev_array_synapses_3_N;
extern __device__ int32_t *d_array_synapses_3_N;
extern const int _num__array_synapses_3_N;
extern int32_t * _array_synapses_4_N;
extern int32_t * dev_array_synapses_4_N;
extern __device__ int32_t *d_array_synapses_4_N;
extern const int _num__array_synapses_4_N;
extern int32_t * _array_synapses_4_sources;
extern int32_t * dev_array_synapses_4_sources;
extern __device__ int32_t *d_array_synapses_4_sources;
extern const int _num__array_synapses_4_sources;
extern int32_t * _array_synapses_4_sources_1;
extern int32_t * dev_array_synapses_4_sources_1;
extern __device__ int32_t *d_array_synapses_4_sources_1;
extern const int _num__array_synapses_4_sources_1;
extern int32_t * _array_synapses_4_sources_2;
extern int32_t * dev_array_synapses_4_sources_2;
extern __device__ int32_t *d_array_synapses_4_sources_2;
extern const int _num__array_synapses_4_sources_2;
extern int32_t * _array_synapses_4_sources_3;
extern int32_t * dev_array_synapses_4_sources_3;
extern __device__ int32_t *d_array_synapses_4_sources_3;
extern const int _num__array_synapses_4_sources_3;
extern int32_t * _array_synapses_4_sources_4;
extern int32_t * dev_array_synapses_4_sources_4;
extern __device__ int32_t *d_array_synapses_4_sources_4;
extern const int _num__array_synapses_4_sources_4;
extern int32_t * _array_synapses_4_sources_5;
extern int32_t * dev_array_synapses_4_sources_5;
extern __device__ int32_t *d_array_synapses_4_sources_5;
extern const int _num__array_synapses_4_sources_5;
extern int32_t * _array_synapses_4_sources_6;
extern int32_t * dev_array_synapses_4_sources_6;
extern __device__ int32_t *d_array_synapses_4_sources_6;
extern const int _num__array_synapses_4_sources_6;
extern int32_t * _array_synapses_4_sources_7;
extern int32_t * dev_array_synapses_4_sources_7;
extern __device__ int32_t *d_array_synapses_4_sources_7;
extern const int _num__array_synapses_4_sources_7;
extern int32_t * _array_synapses_4_sources_8;
extern int32_t * dev_array_synapses_4_sources_8;
extern __device__ int32_t *d_array_synapses_4_sources_8;
extern const int _num__array_synapses_4_sources_8;
extern int32_t * _array_synapses_4_sources_9;
extern int32_t * dev_array_synapses_4_sources_9;
extern __device__ int32_t *d_array_synapses_4_sources_9;
extern const int _num__array_synapses_4_sources_9;
extern int32_t * _array_synapses_4_targets;
extern int32_t * dev_array_synapses_4_targets;
extern __device__ int32_t *d_array_synapses_4_targets;
extern const int _num__array_synapses_4_targets;
extern int32_t * _array_synapses_4_targets_1;
extern int32_t * dev_array_synapses_4_targets_1;
extern __device__ int32_t *d_array_synapses_4_targets_1;
extern const int _num__array_synapses_4_targets_1;
extern int32_t * _array_synapses_4_targets_2;
extern int32_t * dev_array_synapses_4_targets_2;
extern __device__ int32_t *d_array_synapses_4_targets_2;
extern const int _num__array_synapses_4_targets_2;
extern int32_t * _array_synapses_4_targets_3;
extern int32_t * dev_array_synapses_4_targets_3;
extern __device__ int32_t *d_array_synapses_4_targets_3;
extern const int _num__array_synapses_4_targets_3;
extern int32_t * _array_synapses_4_targets_4;
extern int32_t * dev_array_synapses_4_targets_4;
extern __device__ int32_t *d_array_synapses_4_targets_4;
extern const int _num__array_synapses_4_targets_4;
extern int32_t * _array_synapses_4_targets_5;
extern int32_t * dev_array_synapses_4_targets_5;
extern __device__ int32_t *d_array_synapses_4_targets_5;
extern const int _num__array_synapses_4_targets_5;
extern int32_t * _array_synapses_4_targets_6;
extern int32_t * dev_array_synapses_4_targets_6;
extern __device__ int32_t *d_array_synapses_4_targets_6;
extern const int _num__array_synapses_4_targets_6;
extern int32_t * _array_synapses_4_targets_7;
extern int32_t * dev_array_synapses_4_targets_7;
extern __device__ int32_t *d_array_synapses_4_targets_7;
extern const int _num__array_synapses_4_targets_7;
extern int32_t * _array_synapses_4_targets_8;
extern int32_t * dev_array_synapses_4_targets_8;
extern __device__ int32_t *d_array_synapses_4_targets_8;
extern const int _num__array_synapses_4_targets_8;
extern int32_t * _array_synapses_4_targets_9;
extern int32_t * dev_array_synapses_4_targets_9;
extern __device__ int32_t *d_array_synapses_4_targets_9;
extern const int _num__array_synapses_4_targets_9;
extern int32_t * _array_synapses_5_N;
extern int32_t * dev_array_synapses_5_N;
extern __device__ int32_t *d_array_synapses_5_N;
extern const int _num__array_synapses_5_N;
extern int32_t * _array_synapses_5_sources;
extern int32_t * dev_array_synapses_5_sources;
extern __device__ int32_t *d_array_synapses_5_sources;
extern const int _num__array_synapses_5_sources;
extern int32_t * _array_synapses_5_sources_1;
extern int32_t * dev_array_synapses_5_sources_1;
extern __device__ int32_t *d_array_synapses_5_sources_1;
extern const int _num__array_synapses_5_sources_1;
extern int32_t * _array_synapses_5_sources_2;
extern int32_t * dev_array_synapses_5_sources_2;
extern __device__ int32_t *d_array_synapses_5_sources_2;
extern const int _num__array_synapses_5_sources_2;
extern int32_t * _array_synapses_5_sources_3;
extern int32_t * dev_array_synapses_5_sources_3;
extern __device__ int32_t *d_array_synapses_5_sources_3;
extern const int _num__array_synapses_5_sources_3;
extern int32_t * _array_synapses_5_sources_4;
extern int32_t * dev_array_synapses_5_sources_4;
extern __device__ int32_t *d_array_synapses_5_sources_4;
extern const int _num__array_synapses_5_sources_4;
extern int32_t * _array_synapses_5_sources_5;
extern int32_t * dev_array_synapses_5_sources_5;
extern __device__ int32_t *d_array_synapses_5_sources_5;
extern const int _num__array_synapses_5_sources_5;
extern int32_t * _array_synapses_5_sources_6;
extern int32_t * dev_array_synapses_5_sources_6;
extern __device__ int32_t *d_array_synapses_5_sources_6;
extern const int _num__array_synapses_5_sources_6;
extern int32_t * _array_synapses_5_sources_7;
extern int32_t * dev_array_synapses_5_sources_7;
extern __device__ int32_t *d_array_synapses_5_sources_7;
extern const int _num__array_synapses_5_sources_7;
extern int32_t * _array_synapses_5_sources_8;
extern int32_t * dev_array_synapses_5_sources_8;
extern __device__ int32_t *d_array_synapses_5_sources_8;
extern const int _num__array_synapses_5_sources_8;
extern int32_t * _array_synapses_5_sources_9;
extern int32_t * dev_array_synapses_5_sources_9;
extern __device__ int32_t *d_array_synapses_5_sources_9;
extern const int _num__array_synapses_5_sources_9;
extern int32_t * _array_synapses_5_targets;
extern int32_t * dev_array_synapses_5_targets;
extern __device__ int32_t *d_array_synapses_5_targets;
extern const int _num__array_synapses_5_targets;
extern int32_t * _array_synapses_5_targets_1;
extern int32_t * dev_array_synapses_5_targets_1;
extern __device__ int32_t *d_array_synapses_5_targets_1;
extern const int _num__array_synapses_5_targets_1;
extern int32_t * _array_synapses_5_targets_2;
extern int32_t * dev_array_synapses_5_targets_2;
extern __device__ int32_t *d_array_synapses_5_targets_2;
extern const int _num__array_synapses_5_targets_2;
extern int32_t * _array_synapses_5_targets_3;
extern int32_t * dev_array_synapses_5_targets_3;
extern __device__ int32_t *d_array_synapses_5_targets_3;
extern const int _num__array_synapses_5_targets_3;
extern int32_t * _array_synapses_5_targets_4;
extern int32_t * dev_array_synapses_5_targets_4;
extern __device__ int32_t *d_array_synapses_5_targets_4;
extern const int _num__array_synapses_5_targets_4;
extern int32_t * _array_synapses_5_targets_5;
extern int32_t * dev_array_synapses_5_targets_5;
extern __device__ int32_t *d_array_synapses_5_targets_5;
extern const int _num__array_synapses_5_targets_5;
extern int32_t * _array_synapses_5_targets_6;
extern int32_t * dev_array_synapses_5_targets_6;
extern __device__ int32_t *d_array_synapses_5_targets_6;
extern const int _num__array_synapses_5_targets_6;
extern int32_t * _array_synapses_5_targets_7;
extern int32_t * dev_array_synapses_5_targets_7;
extern __device__ int32_t *d_array_synapses_5_targets_7;
extern const int _num__array_synapses_5_targets_7;
extern int32_t * _array_synapses_5_targets_8;
extern int32_t * dev_array_synapses_5_targets_8;
extern __device__ int32_t *d_array_synapses_5_targets_8;
extern const int _num__array_synapses_5_targets_8;
extern int32_t * _array_synapses_5_targets_9;
extern int32_t * dev_array_synapses_5_targets_9;
extern __device__ int32_t *d_array_synapses_5_targets_9;
extern const int _num__array_synapses_5_targets_9;
extern int32_t * _array_synapses_6_N;
extern int32_t * dev_array_synapses_6_N;
extern __device__ int32_t *d_array_synapses_6_N;
extern const int _num__array_synapses_6_N;
extern int32_t * _array_synapses_N;
extern int32_t * dev_array_synapses_N;
extern __device__ int32_t *d_array_synapses_N;
extern const int _num__array_synapses_N;

//////////////// eventspaces ///////////////
extern int32_t * _array_neurongroup_1__spikespace;
extern thrust::host_vector<int32_t*> dev_array_neurongroup_1__spikespace;
extern const int _num__array_neurongroup_1__spikespace;
extern int current_idx_array_neurongroup_1__spikespace;
extern int32_t * _array_neurongroup_2__spikespace;
extern thrust::host_vector<int32_t*> dev_array_neurongroup_2__spikespace;
extern const int _num__array_neurongroup_2__spikespace;
extern int current_idx_array_neurongroup_2__spikespace;
extern int32_t * _array_neurongroup_3__spikespace;
extern thrust::host_vector<int32_t*> dev_array_neurongroup_3__spikespace;
extern const int _num__array_neurongroup_3__spikespace;
extern int current_idx_array_neurongroup_3__spikespace;
extern int32_t * _array_neurongroup__spikespace;
extern thrust::host_vector<int32_t*> dev_array_neurongroup__spikespace;
extern const int _num__array_neurongroup__spikespace;
extern int current_idx_array_neurongroup__spikespace;
extern int32_t * _array_poissongroup_1__spikespace;
extern thrust::host_vector<int32_t*> dev_array_poissongroup_1__spikespace;
extern const int _num__array_poissongroup_1__spikespace;
extern int current_idx_array_poissongroup_1__spikespace;
extern int32_t * _array_poissongroup__spikespace;
extern thrust::host_vector<int32_t*> dev_array_poissongroup__spikespace;
extern const int _num__array_poissongroup__spikespace;
extern int current_idx_array_poissongroup__spikespace;

//////////////// dynamic arrays 2d /////////
extern thrust::device_vector<double*> addresses_monitor__dynamic_array_statemonitor_1_V;
extern thrust::device_vector<double>* _dynamic_array_statemonitor_1_V;
extern thrust::device_vector<double*> addresses_monitor__dynamic_array_statemonitor_2_V;
extern thrust::device_vector<double>* _dynamic_array_statemonitor_2_V;
extern thrust::device_vector<double*> addresses_monitor__dynamic_array_statemonitor_3_V;
extern thrust::device_vector<double>* _dynamic_array_statemonitor_3_V;
extern thrust::device_vector<double*> addresses_monitor__dynamic_array_statemonitor_V;
extern thrust::device_vector<double>* _dynamic_array_statemonitor_V;

/////////////// static arrays /////////////
extern int32_t *_static_array__array_statemonitor_1__indices;
extern int32_t *dev_static_array__array_statemonitor_1__indices;
extern __device__ int32_t *d_static_array__array_statemonitor_1__indices;
extern const int _num__static_array__array_statemonitor_1__indices;
extern int32_t *_static_array__array_statemonitor_2__indices;
extern int32_t *dev_static_array__array_statemonitor_2__indices;
extern __device__ int32_t *d_static_array__array_statemonitor_2__indices;
extern const int _num__static_array__array_statemonitor_2__indices;
extern int32_t *_static_array__array_statemonitor_3__indices;
extern int32_t *dev_static_array__array_statemonitor_3__indices;
extern __device__ int32_t *d_static_array__array_statemonitor_3__indices;
extern const int _num__static_array__array_statemonitor_3__indices;
extern int32_t *_static_array__array_statemonitor__indices;
extern int32_t *dev_static_array__array_statemonitor__indices;
extern __device__ int32_t *d_static_array__array_statemonitor__indices;
extern const int _num__static_array__array_statemonitor__indices;
extern int32_t *_static_array__array_synapses_4_sources;
extern int32_t *dev_static_array__array_synapses_4_sources;
extern __device__ int32_t *d_static_array__array_synapses_4_sources;
extern const int _num__static_array__array_synapses_4_sources;
extern int32_t *_static_array__array_synapses_4_sources_1;
extern int32_t *dev_static_array__array_synapses_4_sources_1;
extern __device__ int32_t *d_static_array__array_synapses_4_sources_1;
extern const int _num__static_array__array_synapses_4_sources_1;
extern int32_t *_static_array__array_synapses_4_sources_2;
extern int32_t *dev_static_array__array_synapses_4_sources_2;
extern __device__ int32_t *d_static_array__array_synapses_4_sources_2;
extern const int _num__static_array__array_synapses_4_sources_2;
extern int32_t *_static_array__array_synapses_4_sources_3;
extern int32_t *dev_static_array__array_synapses_4_sources_3;
extern __device__ int32_t *d_static_array__array_synapses_4_sources_3;
extern const int _num__static_array__array_synapses_4_sources_3;
extern int32_t *_static_array__array_synapses_4_sources_4;
extern int32_t *dev_static_array__array_synapses_4_sources_4;
extern __device__ int32_t *d_static_array__array_synapses_4_sources_4;
extern const int _num__static_array__array_synapses_4_sources_4;
extern int32_t *_static_array__array_synapses_4_sources_5;
extern int32_t *dev_static_array__array_synapses_4_sources_5;
extern __device__ int32_t *d_static_array__array_synapses_4_sources_5;
extern const int _num__static_array__array_synapses_4_sources_5;
extern int32_t *_static_array__array_synapses_4_sources_6;
extern int32_t *dev_static_array__array_synapses_4_sources_6;
extern __device__ int32_t *d_static_array__array_synapses_4_sources_6;
extern const int _num__static_array__array_synapses_4_sources_6;
extern int32_t *_static_array__array_synapses_4_sources_7;
extern int32_t *dev_static_array__array_synapses_4_sources_7;
extern __device__ int32_t *d_static_array__array_synapses_4_sources_7;
extern const int _num__static_array__array_synapses_4_sources_7;
extern int32_t *_static_array__array_synapses_4_sources_8;
extern int32_t *dev_static_array__array_synapses_4_sources_8;
extern __device__ int32_t *d_static_array__array_synapses_4_sources_8;
extern const int _num__static_array__array_synapses_4_sources_8;
extern int32_t *_static_array__array_synapses_4_sources_9;
extern int32_t *dev_static_array__array_synapses_4_sources_9;
extern __device__ int32_t *d_static_array__array_synapses_4_sources_9;
extern const int _num__static_array__array_synapses_4_sources_9;
extern int32_t *_static_array__array_synapses_4_targets;
extern int32_t *dev_static_array__array_synapses_4_targets;
extern __device__ int32_t *d_static_array__array_synapses_4_targets;
extern const int _num__static_array__array_synapses_4_targets;
extern int32_t *_static_array__array_synapses_4_targets_1;
extern int32_t *dev_static_array__array_synapses_4_targets_1;
extern __device__ int32_t *d_static_array__array_synapses_4_targets_1;
extern const int _num__static_array__array_synapses_4_targets_1;
extern int32_t *_static_array__array_synapses_4_targets_2;
extern int32_t *dev_static_array__array_synapses_4_targets_2;
extern __device__ int32_t *d_static_array__array_synapses_4_targets_2;
extern const int _num__static_array__array_synapses_4_targets_2;
extern int32_t *_static_array__array_synapses_4_targets_3;
extern int32_t *dev_static_array__array_synapses_4_targets_3;
extern __device__ int32_t *d_static_array__array_synapses_4_targets_3;
extern const int _num__static_array__array_synapses_4_targets_3;
extern int32_t *_static_array__array_synapses_4_targets_4;
extern int32_t *dev_static_array__array_synapses_4_targets_4;
extern __device__ int32_t *d_static_array__array_synapses_4_targets_4;
extern const int _num__static_array__array_synapses_4_targets_4;
extern int32_t *_static_array__array_synapses_4_targets_5;
extern int32_t *dev_static_array__array_synapses_4_targets_5;
extern __device__ int32_t *d_static_array__array_synapses_4_targets_5;
extern const int _num__static_array__array_synapses_4_targets_5;
extern int32_t *_static_array__array_synapses_4_targets_6;
extern int32_t *dev_static_array__array_synapses_4_targets_6;
extern __device__ int32_t *d_static_array__array_synapses_4_targets_6;
extern const int _num__static_array__array_synapses_4_targets_6;
extern int32_t *_static_array__array_synapses_4_targets_7;
extern int32_t *dev_static_array__array_synapses_4_targets_7;
extern __device__ int32_t *d_static_array__array_synapses_4_targets_7;
extern const int _num__static_array__array_synapses_4_targets_7;
extern int32_t *_static_array__array_synapses_4_targets_8;
extern int32_t *dev_static_array__array_synapses_4_targets_8;
extern __device__ int32_t *d_static_array__array_synapses_4_targets_8;
extern const int _num__static_array__array_synapses_4_targets_8;
extern int32_t *_static_array__array_synapses_4_targets_9;
extern int32_t *dev_static_array__array_synapses_4_targets_9;
extern __device__ int32_t *d_static_array__array_synapses_4_targets_9;
extern const int _num__static_array__array_synapses_4_targets_9;
extern int32_t *_static_array__array_synapses_5_sources;
extern int32_t *dev_static_array__array_synapses_5_sources;
extern __device__ int32_t *d_static_array__array_synapses_5_sources;
extern const int _num__static_array__array_synapses_5_sources;
extern int32_t *_static_array__array_synapses_5_sources_1;
extern int32_t *dev_static_array__array_synapses_5_sources_1;
extern __device__ int32_t *d_static_array__array_synapses_5_sources_1;
extern const int _num__static_array__array_synapses_5_sources_1;
extern int32_t *_static_array__array_synapses_5_sources_2;
extern int32_t *dev_static_array__array_synapses_5_sources_2;
extern __device__ int32_t *d_static_array__array_synapses_5_sources_2;
extern const int _num__static_array__array_synapses_5_sources_2;
extern int32_t *_static_array__array_synapses_5_sources_3;
extern int32_t *dev_static_array__array_synapses_5_sources_3;
extern __device__ int32_t *d_static_array__array_synapses_5_sources_3;
extern const int _num__static_array__array_synapses_5_sources_3;
extern int32_t *_static_array__array_synapses_5_sources_4;
extern int32_t *dev_static_array__array_synapses_5_sources_4;
extern __device__ int32_t *d_static_array__array_synapses_5_sources_4;
extern const int _num__static_array__array_synapses_5_sources_4;
extern int32_t *_static_array__array_synapses_5_sources_5;
extern int32_t *dev_static_array__array_synapses_5_sources_5;
extern __device__ int32_t *d_static_array__array_synapses_5_sources_5;
extern const int _num__static_array__array_synapses_5_sources_5;
extern int32_t *_static_array__array_synapses_5_sources_6;
extern int32_t *dev_static_array__array_synapses_5_sources_6;
extern __device__ int32_t *d_static_array__array_synapses_5_sources_6;
extern const int _num__static_array__array_synapses_5_sources_6;
extern int32_t *_static_array__array_synapses_5_sources_7;
extern int32_t *dev_static_array__array_synapses_5_sources_7;
extern __device__ int32_t *d_static_array__array_synapses_5_sources_7;
extern const int _num__static_array__array_synapses_5_sources_7;
extern int32_t *_static_array__array_synapses_5_sources_8;
extern int32_t *dev_static_array__array_synapses_5_sources_8;
extern __device__ int32_t *d_static_array__array_synapses_5_sources_8;
extern const int _num__static_array__array_synapses_5_sources_8;
extern int32_t *_static_array__array_synapses_5_sources_9;
extern int32_t *dev_static_array__array_synapses_5_sources_9;
extern __device__ int32_t *d_static_array__array_synapses_5_sources_9;
extern const int _num__static_array__array_synapses_5_sources_9;
extern int32_t *_static_array__array_synapses_5_targets;
extern int32_t *dev_static_array__array_synapses_5_targets;
extern __device__ int32_t *d_static_array__array_synapses_5_targets;
extern const int _num__static_array__array_synapses_5_targets;
extern int32_t *_static_array__array_synapses_5_targets_1;
extern int32_t *dev_static_array__array_synapses_5_targets_1;
extern __device__ int32_t *d_static_array__array_synapses_5_targets_1;
extern const int _num__static_array__array_synapses_5_targets_1;
extern int32_t *_static_array__array_synapses_5_targets_2;
extern int32_t *dev_static_array__array_synapses_5_targets_2;
extern __device__ int32_t *d_static_array__array_synapses_5_targets_2;
extern const int _num__static_array__array_synapses_5_targets_2;
extern int32_t *_static_array__array_synapses_5_targets_3;
extern int32_t *dev_static_array__array_synapses_5_targets_3;
extern __device__ int32_t *d_static_array__array_synapses_5_targets_3;
extern const int _num__static_array__array_synapses_5_targets_3;
extern int32_t *_static_array__array_synapses_5_targets_4;
extern int32_t *dev_static_array__array_synapses_5_targets_4;
extern __device__ int32_t *d_static_array__array_synapses_5_targets_4;
extern const int _num__static_array__array_synapses_5_targets_4;
extern int32_t *_static_array__array_synapses_5_targets_5;
extern int32_t *dev_static_array__array_synapses_5_targets_5;
extern __device__ int32_t *d_static_array__array_synapses_5_targets_5;
extern const int _num__static_array__array_synapses_5_targets_5;
extern int32_t *_static_array__array_synapses_5_targets_6;
extern int32_t *dev_static_array__array_synapses_5_targets_6;
extern __device__ int32_t *d_static_array__array_synapses_5_targets_6;
extern const int _num__static_array__array_synapses_5_targets_6;
extern int32_t *_static_array__array_synapses_5_targets_7;
extern int32_t *dev_static_array__array_synapses_5_targets_7;
extern __device__ int32_t *d_static_array__array_synapses_5_targets_7;
extern const int _num__static_array__array_synapses_5_targets_7;
extern int32_t *_static_array__array_synapses_5_targets_8;
extern int32_t *dev_static_array__array_synapses_5_targets_8;
extern __device__ int32_t *d_static_array__array_synapses_5_targets_8;
extern const int _num__static_array__array_synapses_5_targets_8;
extern int32_t *_static_array__array_synapses_5_targets_9;
extern int32_t *dev_static_array__array_synapses_5_targets_9;
extern __device__ int32_t *d_static_array__array_synapses_5_targets_9;
extern const int _num__static_array__array_synapses_5_targets_9;

//////////////// synapses /////////////////
// synapses
extern bool synapses_multiple_pre_post;
extern __device__ int* synapses_post_num_synapses_by_pre;
extern __device__ int* synapses_post_num_synapses_by_bundle;
extern __device__ int* synapses_post_unique_delays;
extern __device__ int* synapses_post_synapses_offset_by_bundle;
extern __device__ int* synapses_post_global_bundle_id_start_by_pre;
extern int synapses_post_max_bundle_size;
extern int synapses_post_mean_bundle_size;
extern int synapses_post_max_size;
extern __device__ int* synapses_post_num_unique_delays_by_pre;
extern int synapses_post_max_num_unique_delays;
extern __device__ int32_t** synapses_post_synapse_ids_by_pre;
extern __device__ int32_t* synapses_post_synapse_ids;
extern __device__ int* synapses_post_unique_delay_start_idcs;
extern __device__ int* synapses_post_unique_delays_offset_by_pre;
extern __device__ SynapticPathway synapses_post;
extern int synapses_post_eventspace_idx;
extern int synapses_post_delay;
extern bool synapses_post_scalar_delay;
extern __device__ int* synapses_pre_num_synapses_by_pre;
extern __device__ int* synapses_pre_num_synapses_by_bundle;
extern __device__ int* synapses_pre_unique_delays;
extern __device__ int* synapses_pre_synapses_offset_by_bundle;
extern __device__ int* synapses_pre_global_bundle_id_start_by_pre;
extern int synapses_pre_max_bundle_size;
extern int synapses_pre_mean_bundle_size;
extern int synapses_pre_max_size;
extern __device__ int* synapses_pre_num_unique_delays_by_pre;
extern int synapses_pre_max_num_unique_delays;
extern __device__ int32_t** synapses_pre_synapse_ids_by_pre;
extern __device__ int32_t* synapses_pre_synapse_ids;
extern __device__ int* synapses_pre_unique_delay_start_idcs;
extern __device__ int* synapses_pre_unique_delays_offset_by_pre;
extern __device__ SynapticPathway synapses_pre;
extern int synapses_pre_eventspace_idx;
extern int synapses_pre_delay;
extern bool synapses_pre_scalar_delay;
// synapses_1
extern bool synapses_1_multiple_pre_post;
extern __device__ int* synapses_1_post_num_synapses_by_pre;
extern __device__ int* synapses_1_post_num_synapses_by_bundle;
extern __device__ int* synapses_1_post_unique_delays;
extern __device__ int* synapses_1_post_synapses_offset_by_bundle;
extern __device__ int* synapses_1_post_global_bundle_id_start_by_pre;
extern int synapses_1_post_max_bundle_size;
extern int synapses_1_post_mean_bundle_size;
extern int synapses_1_post_max_size;
extern __device__ int* synapses_1_post_num_unique_delays_by_pre;
extern int synapses_1_post_max_num_unique_delays;
extern __device__ int32_t** synapses_1_post_synapse_ids_by_pre;
extern __device__ int32_t* synapses_1_post_synapse_ids;
extern __device__ int* synapses_1_post_unique_delay_start_idcs;
extern __device__ int* synapses_1_post_unique_delays_offset_by_pre;
extern __device__ SynapticPathway synapses_1_post;
extern int synapses_1_post_eventspace_idx;
extern int synapses_1_post_delay;
extern bool synapses_1_post_scalar_delay;
extern __device__ int* synapses_1_pre_num_synapses_by_pre;
extern __device__ int* synapses_1_pre_num_synapses_by_bundle;
extern __device__ int* synapses_1_pre_unique_delays;
extern __device__ int* synapses_1_pre_synapses_offset_by_bundle;
extern __device__ int* synapses_1_pre_global_bundle_id_start_by_pre;
extern int synapses_1_pre_max_bundle_size;
extern int synapses_1_pre_mean_bundle_size;
extern int synapses_1_pre_max_size;
extern __device__ int* synapses_1_pre_num_unique_delays_by_pre;
extern int synapses_1_pre_max_num_unique_delays;
extern __device__ int32_t** synapses_1_pre_synapse_ids_by_pre;
extern __device__ int32_t* synapses_1_pre_synapse_ids;
extern __device__ int* synapses_1_pre_unique_delay_start_idcs;
extern __device__ int* synapses_1_pre_unique_delays_offset_by_pre;
extern __device__ SynapticPathway synapses_1_pre;
extern int synapses_1_pre_eventspace_idx;
extern int synapses_1_pre_delay;
extern bool synapses_1_pre_scalar_delay;
// synapses_2
extern bool synapses_2_multiple_pre_post;
extern __device__ int* synapses_2_post_num_synapses_by_pre;
extern __device__ int* synapses_2_post_num_synapses_by_bundle;
extern __device__ int* synapses_2_post_unique_delays;
extern __device__ int* synapses_2_post_synapses_offset_by_bundle;
extern __device__ int* synapses_2_post_global_bundle_id_start_by_pre;
extern int synapses_2_post_max_bundle_size;
extern int synapses_2_post_mean_bundle_size;
extern int synapses_2_post_max_size;
extern __device__ int* synapses_2_post_num_unique_delays_by_pre;
extern int synapses_2_post_max_num_unique_delays;
extern __device__ int32_t** synapses_2_post_synapse_ids_by_pre;
extern __device__ int32_t* synapses_2_post_synapse_ids;
extern __device__ int* synapses_2_post_unique_delay_start_idcs;
extern __device__ int* synapses_2_post_unique_delays_offset_by_pre;
extern __device__ SynapticPathway synapses_2_post;
extern int synapses_2_post_eventspace_idx;
extern int synapses_2_post_delay;
extern bool synapses_2_post_scalar_delay;
extern __device__ int* synapses_2_pre_num_synapses_by_pre;
extern __device__ int* synapses_2_pre_num_synapses_by_bundle;
extern __device__ int* synapses_2_pre_unique_delays;
extern __device__ int* synapses_2_pre_synapses_offset_by_bundle;
extern __device__ int* synapses_2_pre_global_bundle_id_start_by_pre;
extern int synapses_2_pre_max_bundle_size;
extern int synapses_2_pre_mean_bundle_size;
extern int synapses_2_pre_max_size;
extern __device__ int* synapses_2_pre_num_unique_delays_by_pre;
extern int synapses_2_pre_max_num_unique_delays;
extern __device__ int32_t** synapses_2_pre_synapse_ids_by_pre;
extern __device__ int32_t* synapses_2_pre_synapse_ids;
extern __device__ int* synapses_2_pre_unique_delay_start_idcs;
extern __device__ int* synapses_2_pre_unique_delays_offset_by_pre;
extern __device__ SynapticPathway synapses_2_pre;
extern int synapses_2_pre_eventspace_idx;
extern int synapses_2_pre_delay;
extern bool synapses_2_pre_scalar_delay;
// synapses_3
extern bool synapses_3_multiple_pre_post;
extern __device__ int* synapses_3_pre_num_synapses_by_pre;
extern __device__ int* synapses_3_pre_num_synapses_by_bundle;
extern __device__ int* synapses_3_pre_unique_delays;
extern __device__ int* synapses_3_pre_synapses_offset_by_bundle;
extern __device__ int* synapses_3_pre_global_bundle_id_start_by_pre;
extern int synapses_3_pre_max_bundle_size;
extern int synapses_3_pre_mean_bundle_size;
extern int synapses_3_pre_max_size;
extern __device__ int* synapses_3_pre_num_unique_delays_by_pre;
extern int synapses_3_pre_max_num_unique_delays;
extern __device__ int32_t** synapses_3_pre_synapse_ids_by_pre;
extern __device__ int32_t* synapses_3_pre_synapse_ids;
extern __device__ int* synapses_3_pre_unique_delay_start_idcs;
extern __device__ int* synapses_3_pre_unique_delays_offset_by_pre;
extern __device__ SynapticPathway synapses_3_pre;
extern int synapses_3_pre_eventspace_idx;
extern int synapses_3_pre_delay;
extern bool synapses_3_pre_scalar_delay;
// synapses_4
extern bool synapses_4_multiple_pre_post;
extern __device__ int* synapses_4_post_num_synapses_by_pre;
extern __device__ int* synapses_4_post_num_synapses_by_bundle;
extern __device__ int* synapses_4_post_unique_delays;
extern __device__ int* synapses_4_post_synapses_offset_by_bundle;
extern __device__ int* synapses_4_post_global_bundle_id_start_by_pre;
extern int synapses_4_post_max_bundle_size;
extern int synapses_4_post_mean_bundle_size;
extern int synapses_4_post_max_size;
extern __device__ int* synapses_4_post_num_unique_delays_by_pre;
extern int synapses_4_post_max_num_unique_delays;
extern __device__ int32_t** synapses_4_post_synapse_ids_by_pre;
extern __device__ int32_t* synapses_4_post_synapse_ids;
extern __device__ int* synapses_4_post_unique_delay_start_idcs;
extern __device__ int* synapses_4_post_unique_delays_offset_by_pre;
extern __device__ SynapticPathway synapses_4_post;
extern int synapses_4_post_eventspace_idx;
extern int synapses_4_post_delay;
extern bool synapses_4_post_scalar_delay;
extern __device__ int* synapses_4_pre_num_synapses_by_pre;
extern __device__ int* synapses_4_pre_num_synapses_by_bundle;
extern __device__ int* synapses_4_pre_unique_delays;
extern __device__ int* synapses_4_pre_synapses_offset_by_bundle;
extern __device__ int* synapses_4_pre_global_bundle_id_start_by_pre;
extern int synapses_4_pre_max_bundle_size;
extern int synapses_4_pre_mean_bundle_size;
extern int synapses_4_pre_max_size;
extern __device__ int* synapses_4_pre_num_unique_delays_by_pre;
extern int synapses_4_pre_max_num_unique_delays;
extern __device__ int32_t** synapses_4_pre_synapse_ids_by_pre;
extern __device__ int32_t* synapses_4_pre_synapse_ids;
extern __device__ int* synapses_4_pre_unique_delay_start_idcs;
extern __device__ int* synapses_4_pre_unique_delays_offset_by_pre;
extern __device__ SynapticPathway synapses_4_pre;
extern int synapses_4_pre_eventspace_idx;
extern int synapses_4_pre_delay;
extern bool synapses_4_pre_scalar_delay;
// synapses_5
extern bool synapses_5_multiple_pre_post;
extern __device__ int* synapses_5_post_num_synapses_by_pre;
extern __device__ int* synapses_5_post_num_synapses_by_bundle;
extern __device__ int* synapses_5_post_unique_delays;
extern __device__ int* synapses_5_post_synapses_offset_by_bundle;
extern __device__ int* synapses_5_post_global_bundle_id_start_by_pre;
extern int synapses_5_post_max_bundle_size;
extern int synapses_5_post_mean_bundle_size;
extern int synapses_5_post_max_size;
extern __device__ int* synapses_5_post_num_unique_delays_by_pre;
extern int synapses_5_post_max_num_unique_delays;
extern __device__ int32_t** synapses_5_post_synapse_ids_by_pre;
extern __device__ int32_t* synapses_5_post_synapse_ids;
extern __device__ int* synapses_5_post_unique_delay_start_idcs;
extern __device__ int* synapses_5_post_unique_delays_offset_by_pre;
extern __device__ SynapticPathway synapses_5_post;
extern int synapses_5_post_eventspace_idx;
extern int synapses_5_post_delay;
extern bool synapses_5_post_scalar_delay;
extern __device__ int* synapses_5_pre_num_synapses_by_pre;
extern __device__ int* synapses_5_pre_num_synapses_by_bundle;
extern __device__ int* synapses_5_pre_unique_delays;
extern __device__ int* synapses_5_pre_synapses_offset_by_bundle;
extern __device__ int* synapses_5_pre_global_bundle_id_start_by_pre;
extern int synapses_5_pre_max_bundle_size;
extern int synapses_5_pre_mean_bundle_size;
extern int synapses_5_pre_max_size;
extern __device__ int* synapses_5_pre_num_unique_delays_by_pre;
extern int synapses_5_pre_max_num_unique_delays;
extern __device__ int32_t** synapses_5_pre_synapse_ids_by_pre;
extern __device__ int32_t* synapses_5_pre_synapse_ids;
extern __device__ int* synapses_5_pre_unique_delay_start_idcs;
extern __device__ int* synapses_5_pre_unique_delays_offset_by_pre;
extern __device__ SynapticPathway synapses_5_pre;
extern int synapses_5_pre_eventspace_idx;
extern int synapses_5_pre_delay;
extern bool synapses_5_pre_scalar_delay;
// synapses_6
extern bool synapses_6_multiple_pre_post;
extern __device__ int* synapses_6_pre_num_synapses_by_pre;
extern __device__ int* synapses_6_pre_num_synapses_by_bundle;
extern __device__ int* synapses_6_pre_unique_delays;
extern __device__ int* synapses_6_pre_synapses_offset_by_bundle;
extern __device__ int* synapses_6_pre_global_bundle_id_start_by_pre;
extern int synapses_6_pre_max_bundle_size;
extern int synapses_6_pre_mean_bundle_size;
extern int synapses_6_pre_max_size;
extern __device__ int* synapses_6_pre_num_unique_delays_by_pre;
extern int synapses_6_pre_max_num_unique_delays;
extern __device__ int32_t** synapses_6_pre_synapse_ids_by_pre;
extern __device__ int32_t* synapses_6_pre_synapse_ids;
extern __device__ int* synapses_6_pre_unique_delay_start_idcs;
extern __device__ int* synapses_6_pre_unique_delays_offset_by_pre;
extern __device__ SynapticPathway synapses_6_pre;
extern int synapses_6_pre_eventspace_idx;
extern int synapses_6_pre_delay;
extern bool synapses_6_pre_scalar_delay;

// Profiling information for each code object

//////////////// random numbers /////////////////
extern curandGenerator_t curand_generator;
extern unsigned long long* dev_curand_seed;
extern __device__ unsigned long long* d_curand_seed;

// pointer to start of generated random numbers array
// at each generation cycle this array is refilled
extern randomNumber_t* dev_poissongroup_1_thresholder_codeobject_rand_allocator;
// pointer moving through generated random number array
// until it is regenerated at the next generation cycle
extern randomNumber_t* dev_poissongroup_1_thresholder_codeobject_rand;
extern __device__ randomNumber_t* _array_poissongroup_1_thresholder_codeobject_rand;
// pointer to start of generated random numbers array
// at each generation cycle this array is refilled
extern randomNumber_t* dev_poissongroup_thresholder_codeobject_rand_allocator;
// pointer moving through generated random number array
// until it is regenerated at the next generation cycle
extern randomNumber_t* dev_poissongroup_thresholder_codeobject_rand;
extern __device__ randomNumber_t* _array_poissongroup_thresholder_codeobject_rand;
extern curandState* dev_curand_states;
extern __device__ curandState* d_curand_states;
extern RandomNumberBuffer random_number_buffer;

//CUDA
extern int num_parallel_blocks;
extern int max_threads_per_block;
extern int max_threads_per_sm;
extern int max_shared_mem_size;
extern int num_threads_per_warp;

}

void _init_arrays();
void _load_arrays();
void _write_arrays();
void _dealloc_arrays();

#endif


